# -*-python-*-
import os
from site_init import *

texi_includes = ['examples', 'images']
subdirs = texi_includes + ['css']

# importing whole of os.environ is a very bad idea
env = Environment (tools=['default', add_texi2html_builder],
                   ENV=os.environ,
                   OUT='out',
                   TEXINFO_PATH=texi_includes)

# The actual build rules
env.texiBuild ('$OUT/lilypnod-general.html', 'lilypond-general.texi')
[env.Install (env['OUT'], Glob (dir + '/*')) for dir in subdirs]
