import TaskGen

tely = []
lilypond_book = ''

texi = ['contributor.texi']
texi2pdf_rule = 'texi2pdf -I default/Documentation/ -o ${TGT} ${SRC}'
texi2html_rule = 'texi2html -I default/Documentation/ -o ${TGT} ${SRC}'


def build(bld):
    bld.new_task_gen(
         target = 'version.itexi',
         rule = 'python ' + bld.env['top-src-dir'] + '/build/helper/create-version-itexi.py > ${TGT}',
    )

    # convert tely -> texi


    # texi -> pdf, html
    for src in texi:
        base_target = src.split('.')[0]
        bld.new_task_gen (after = 'version.itexi',
            source = src,
            target = base_target + '.pdf',
            rule = texi2pdf_rule
        )
        bld.new_task_gen (after = 'version.itexi',
            source = src,
            target = base_target + '.html',
            rule = texi2html_rule
        )


